language: python

python:
  - 2.7

services: postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE=rawblog.settings.test
    - SECRET_KEY=TRAVIS_SECRET_KEY

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test