language: python

python:
  - 2.7

services: postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE=rawblog.settings.test
    - SECRET_KEY=TRAVIS_SECRET_KEY
    - DATABASE_URL=postgres://postgres@localhost/raw_test

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c "CREATE DATABASE raw_test;" -U postgres
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - coverage run --source=rawauth,blog manage.py test

after_success:
  - coveralls