language: python

python:
  - 2.7

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=rawblog.settings.test
  - export SECRET_KEY=TRAVIS_SECRET_KEY

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE raw_test;" -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py test